[workspace]
members = [
    "crates/evm_opcodes",
    "output/*",
]

[workspace.package]
homepage = "https://github.com/Oxidefier"
edition = "2021"

[workspace.dependencies]
evm_opcodes = { path = "crates/evm_opcodes" }

alloy-primitives = { version = "1.0" }
