[package]
name = "out"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy-primitives = { version = "1.0", default-features = false }

[lib]
path = "out.rs"

[[bin]]
name = "out"
path = "out.rs"
