name: Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download Git submodules
      run: git submodule update --init --recursive
    - name: Install Solidity
      run: |
        sudo add-apt-repository ppa:ethereum/ethereum
        sudo apt-get update
        sudo apt-get install -y solc
    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source "$HOME/.cargo/env"
        rustup toolchain install nightly-2024-12-07-x86_64-unknown-linux-gnu
        cargo --version
        sudo chown -R $(whoami) .
    # - name: Translate to Yul JSON
    #   run: |
    #     for dir in contracts/*; do
    #       solc --ir-optimized-ast-json --optimize --yul-optimizations hg $dir/contract.sol \
    #         | tail -1 \
    #         > $dir/contract.json
    #     done
    - name: Translate to Rust
      run: |
        for dir in contracts/*; do
          echo "Translating $dir"
          python oxidefier.py $dir/contract.json ${dir##*/}
          echo
        done
    - name: Build
      run: cargo check
    - name: Check that the diff is empty (excluding submodules)
      run: git -c color.ui=always diff --exit-code --ignore-submodules=dirty
